stages:
  - install
  - test
  - deploy

default:
  image: saez-juan/lighting-node:v1

# == Cache

.node_modules-cache: &node_modules-cache
  key:
    files:
      - package-lock.json
  paths:
    - node_modules

# == Jobs

install_dependencies:
  stage: install
  variables:
    FF_USE_FASTZIP: 'true'
    CACHE_COMPRESSION_LEVEL: 'fast'
  script:
    - npm ci
  cache:
    - <<: *node_modules-cache
      policy: push
  only:
    changes:
      - package-lock.json

pages:
  stage: deploy
  script:
    - npm run build
    - cp -a build/. public
  cache:
    - <<: *node_modules-cache
      policy: pull
  artifacts:
    paths:
      - public
  only:
    refs:
      - main
